# Generated by Django 2.2.6 on 2020-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_follow'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed', through='feedpage.Follow', to='accounts.Profile'),
        ),
    ]
