# Generated by Django 2.2.6 on 2020-05-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_auto_20200525_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedcomment',
            old_name='liked_users',
            new_name='comment_liked_users',
        ),
    ]
