# Generated by Django 2.2.6 on 2020-06-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_feed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='feed_photos'),
        ),
    ]
