# Generated by Django 2.2.6 on 2020-05-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0007_auto_20200525_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='liked_users',
            new_name='hi_liked_users',
        ),
    ]
