# Generated by Django 2.2.6 on 2020-05-25 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0009_auto_20200525_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='hi_liked_users',
            new_name='liked_users',
        ),
        migrations.RenameField(
            model_name='feedcomment',
            old_name='comment_liked_users',
            new_name='liked_users',
        ),
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.FeedComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
