# Generated by Django 2.2.6 on 2020-05-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0011_auto_20200525_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_liked', through='feedpage.CommentLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
