# Generated by Django 2.2.6 on 2020-05-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0013_auto_20200525_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
        ),
    ]
