# Generated by Django 2.2.6 on 2020-05-25 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0017_auto_20200525_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
            preserve_default=False,
        ),
    ]
