# Generated by Django 2.2.6 on 2020-05-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0018_auto_20200525_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcomment',
            name='liked_users',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
